### ISSUE TITLE
Do not put code in folders

### ISSUE THREAD

**Issue by melanietreitinger** [eledia/block_eledia_generate_multikeys#1]
It is not convenient to have the repo code in folders.
This prevents the usage of this plugin as submodule!
Can you please put the files directly in the main folders of the repository, as it is standard github practise?

**Comment by eledia** [comment]
The published repositories here are directly pushed from our internal git were we need this structure. We want to be able to merge our plugins directly into a moodle repository without the usage of submodules. We will not reformat this for publishing.
